# Generated by Django 4.0.4 on 2022-04-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_tipos_protudos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protudos',
            name='preparation_time',
            field=models.CharField(max_length=70),
        ),
    ]
