# Generated by Django 4.0.4 on 2022-04-28 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_recipe_category_receitas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receitas',
            name='author',
        ),
        migrations.RemoveField(
            model_name='receitas',
            name='category',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='author',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Receitas',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
