# Generated by Django 4.0.4 on 2022-04-25 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20220421_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipe.category'),
        ),
    ]
