# Generated by Django 4.0.4 on 2022-04-28 13:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0004_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receitas',
            new_name='Receita',
        ),
    ]
