# Generated by Django 4.0.4 on 2022-04-28 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_rename_receitas_receita'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receita',
        ),
    ]
